config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  match '/home', to: 'pages#index', via: [:get, :post]
  match '/group', to: 'pages#group', via: [:get, :post]
  match '/home_fixed', to: 'pages#index_fixed', via: [:get, :post]
  match '/group_fixed', to: 'pages#group_fixed', via: [:get, :post]
end

app/views/layouts/_correlation.html.haml
= raw "r = (∑x<sub>i</sub>y<sub>i</sub> - n<span style='text-decoration: overline'>x</span><span style='text-decoration: overline'>y</span>) / (nσ<sub>x</sub>σ<sub>y</sub>)"
%br
= raw "r = (#{ selection.xy_sum } - #{ selection.cohorts.count} * #{ selection.x_mean } * #{ selection.y_mean.round(3) }) / (#{ selection.cohorts.count} * #{ selection.x_deviation.round(3) } * #{ selection.y_deviation.round(3) })"
%br
= raw "r ≈ #{ selection.correlation.round(3) }"
%br
%br
%span{ style: 'color: red'}
  Коефіцієнт кореляції:&nbsp;
  = selection.correlation.round(3)
  %br
  - if (selection.correlation).abs < 0.1
    Коефіцієнт кореляції близький до нуля - значить кількість патологій у дітей майже не залежить від віку
  - else
    Коефіцієнт кореляції відмінний від нуля - значить кількість патологій у дітей суттєво залежить від віку
  %br
  - if selection.correlation > 0
    Кореляція - додатнє число значить залежність прямопропорційна. Тобто з віком кількість патологій ШКТ зростає.
  - else
    Кореляція - від'ємне число значить залежність оберненопропорційна. Тобто з віком кількість патологій ШКТ зменшується.
  %br

app/views/layouts/_dispersion_calculation.html.haml
%table.au
  %tr
    %td
    - selection.cohorts.each do |group|
      %td
    %td
      = "∑#{ symbol }"
      %sub i
    %td
      = raw "<span style='text-decoration: overline'>#{ symbol }</span>"
  %tr
    %td
      = symbol
      %sub
        i
    - selection.send("#{ symbol }_data").each do |group|
      %td
        = group
    %td
      = selection.send("#{ symbol }_total")
    %td
      = selection.send("#{ symbol }_mean").round(3)
  %tr
    %td
      = raw("(#{ symbol }<sub>i</sub>-<span style='text-decoration: overline'>#{ symbol }</span>)<sup>2</sup>")
    - selection.send("#{ symbol }_squares").each do |item|
      %td
        = item.round(3)
    %td
      = selection.send("#{ symbol }_squares_sum").round(3)
    %td
      = selection.send("#{ symbol }_dispersion").round(3)

%br
Вибіркове середнє:
%span{ style: 'text-decoration: overline' }
  = symbol
= '='
= raw "∑#{ symbol }<sub>i</sub> / #{ selection.cohorts.count } = #{ selection.send("#{ symbol }_total") } / #{ selection.cohorts.count } = #{ selection.send("#{ symbol }_mean").round(3) }"
%br
%br
Вибіркова дисперсія:
%span{ style: 'text-decoration: overline'}
  D
%sub
  = symbol
  = '='
= raw "∑(#{ symbol }<sub>i</sub>-<span style='text-decoration: overline'>#{ symbol }</span>)<sup>2</sup> / n = "
= "#{ selection.send("#{ symbol }_squares_sum").round(3) } / #{ selection.cohorts.count } = #{ selection.send("#{ symbol }_dispersion").round(3) }"
%br
%br
Вибіркове квадратичне відхилення:
= raw "σ<sub>#{ symbol }</sub> = √<span style='text-decoration: overline'>D</span><sub>#{ symbol }</sub> ≈ #{ selection.send("#{ symbol }_deviation").round(3)  }"
%br
%br

app/views/layouts/_errors.html.haml
S<sub>e</sub><sup>2</sup> - (означає залишкове відхилення регресії, що являє собою оцінку дисперсії σ<sub>y</sub> в тому випадку якщо модель вірна).
%br
%br
S<sub>e</sub><sup>2</sup> = ∑(y-<span style='text-decoration: overline'>y</span>)<sup>2</sup> / n-2 =
= "#{ selection.send("y_squares_sum").round(3) } / #{ selection.group_numbers.count }-2 = "
= "#{ selection.se2.round(3) }"
%br
%br
Стандартні похибки коефіціентів кореляції:
%br
%br
S<sub>A</sub> = S<sub>e</sub>(√(1/n + <span style='text-decoration: overline'>x</span><sup>2</sup>/∑(x-<span style='text-decoration: overline'>x</span>)<sup>2</sup>))
%br
S<sub>A</sub> =
= raw "#{ selection.se.round(3) }(√(1/#{ selection.group_numbers.count } + #{ selection.x_mean}<sup>2</sup>/#{ selection.y_squares_sum.round(3) })"
%br
S<sub>A</sub> =
= selection.sa.round(3)
%br
%br
A =
= "#{ selection.regression[:a] } ± #{ selection.sa.round(3) }t "
%br
%span{style: 'color: red'}
  A =
  = "#{ selection.regression[:a] } ± #{ (selection.sa* selection.student).round(3)  }"
%br
%br
S<sub>B</sub> = S<sub>e</sub>(√(1/∑(x-<span style='text-decoration: overline'>x</span>)<sup>2</sup>))
%br
S<sub>B</sub> =
= "#{ selection.se.round(3) }(√(1/#{ selection.y_squares_sum.round(3) })"
%br
S<sub>B</sub> =
= selection.sb.round(3)
%br
%br
B =
= "#{ selection.regression[:b] } ± #{ selection.sb.round(3) }t "
%br
%span{style: 'color: red'}
  B =
  = "#{ selection.regression[:b] } ± #{ (selection.sb* selection.student).round(3)  }"
%br
%br
Зазвичай істинні величини коєфіціентів невідомі. Відомі тільки їх оцінки A і B. Інакше кажучи, істинна пряма регресії може пройти інакше, ніж побудована по даним вибірки.
Порахуємо довірчу область для лінії регресії. При будь-якому значенні x відповідні значення y розподілені нормально. Середнім є значення  рівняння регресії
<span style='text-decoration: overline'>y</span>. Невизначеність його оцігки характеризується стандартною похибкою регресії:
%br
%br
S<sub><span style='text-decoration: overline'>y</span></sub> = S<sub>e</sub>(√(1/n + (x-<span style='text-decoration: overline'>x</span>)<sup>2</sup>/∑(x<sub>i</sub>-<span style='text-decoration: overline'>x</span>)<sup>2</sup>))
%br
%br
Порахуємо 95% - довірчий інтервал для значення рівняння регресії в точці х:
%br
%br
<span style='text-decoration: overline'>y</span> - tS<sub><span style='text-decoration: overline'>y</span></sub> < y < S<span style='text-decoration: overline'>y</span> + tS<sub><span style='text-decoration: overline'>y</span></sub>
%br
%br
t - значення коефіціента Стюдента(взято з таблиці) для 95% імовірності і n-2 степенів свободи(кількість вимірів).
%br
%br
%span{ style: 'color: red'}
  t =
  = selection.student
%br
%br
Довірча облясть лінії регресії позначенаголубою лінією. З 95% - імовірністю можна стверджувати що істинна лінія знаходиться десь всередині цієї області.
Або інакше, якщо ми зберемо аналогічні набори даних і побудуємо по них лінію регресії то в 95% випадків ці прямі не покинуть границь довірчої області.
%br
%br
Зверни увагу, що деякі точки знаходяться поза довірчою областю. Це правильно, бо річ іде про довірчу область лінії регресії а не самих значень.
%br
%br
Розкид значень складується з розкиду значень навколо лінії регресії і неоднозначность положення самої цієї лінії:
%br
%br
S<sub>y</sub> = S<sub>e</sub>(√(1/m + 1/n + (x-<span style='text-decoration: overline'>x</span>)<sup>2</sup>/∑(x<sub>i</sub>-<span style='text-decoration: overline'>x</span>)<sup>2</sup>))
%br
%br
Тут m - кратність вимірювання при даному х. 95%-відсотковий довірчий інтевал(інтервал прогнозу) для середнього з m значень буде:
%br
%br
<span style='text-decoration: overline'>y</span> - tS<sub>y</sub> < y < Sy + tS<sub><span style='text-decoration: overline'>y</span></sub>
%br
%br
На графіку эта 95% довірча область при m=1 обмежена червоними лініями. В цю область потрапляє 95 %  всіх можливих значень величини y досліджуваному діапазоні значень x.

app/views/layouts/_regression.html.haml
y - <span style='text-decoration: overline'>y</span> =
r(σ<sub>y</sub>/σ<sub>x</sub>)(x-<span style='text-decoration: overline'>x</span>)
%br
= "y - #{ selection.y_mean.round(3) } = #{ selection.correlation.round(3) }(#{ selection.y_deviation.round(3) } / #{ selection.x_deviation.round(3) })(x - #{ selection.x_mean.round(3) })"
%br
= "y = (#{ selection.correlation.round(3) }(#{ selection.y_deviation.round(3) } / #{ selection.x_deviation.round(3) }))x -"
= " (#{ selection.correlation.round(3) }(#{ selection.y_deviation.round(3)  } / #{ selection.x_deviation.round(3)  }))#{ selection.x_mean.round(3) }) + (#{ selection.y_mean.round(3) })"
%br
= "y = #{ (selection.correlation * ( selection.y_deviation  /  selection.x_deviation )).round(3) }x - "
= "(#{ (selection.correlation * (  selection.y_deviation  /  selection.x_deviation ) * selection.x_mean ).round(3) }) + #{ selection.y_mean.round(3) }"
%br
= "y = #{ selection.regression[:b].round(3) }x + #{ selection.regression[:a].round(3) }"
%br
%br
%span{ style: 'color: red'}
  Рівняння регресії:&nbsp;
  Y = A + BX
  %br
  а в нас вийшло:&nbsp
  %br
  = "Y = #{ selection.regression[:a].round(3)} + #{selection.regression[:b].round(3)}X"
%br
значить
%br

%span{ style: 'color: red'}
  = "A = #{ selection.regression[:a].round(3)}"
  %br
  = "B = #{ selection.regression[:b].round(3)}"
%br
%br
Ці числа не мають фізичного змісту !!! Це не вік і не не кількість патологій, а просто коефіціенти пропорційності.
%br
Фізичний зміст мають x - вікова група (не вік !!!) і y - кількість дітей/патологій в даній групі.
%br
Коефіціент A каже нам на скільки рівняння регресії піднято(чи опущено на віссю іксів)
%br
Коефіціент B каже нам на скільки рівняння регресії нахилено. Фактично це фізична швидкість. Тобто як швидко кількість патологі зменшується з віком.
%br
- if selection.correlation < 0
  Який висновок можна зробити?
  %br
  Продовжимо рфвняння регресії так щоб воно пересіклося з віссю X
  %br
  В цьому випадку Y буде рівний 0
  %br
  %br
  Y = 0
  %br
  %br
  яка буде в нас в цій точці вікова група(Y) ?
  %br
  Підставляємо наш Y = 0 у рівняння
  %br
  %br
  = "#{ selection.regression[:a].round(3)} + #{selection.regression[:b].round(3)}X = 0"
  %br
  = "#{selection.regression[:b].round(3) * -1 }X = #{ selection.regression[:a].round(3)}"
  %br
  = "X = #{ selection.regression[:a].round(3)} / #{selection.regression[:b].round(3) * -1 }"
  %br
  = "X = #{ value = selection.regression[:a] / selection.regression[:b].round(3) * -1 }"
  %br
  %br
  це для простої регресії. а шо буде для груп ?
  %br
  так як група не може бути дробовим числом. бо це просто порядковий номер 1,2,3,4...
  %br
  заокруглюємо групу до більшого
  %br
  %br
  = "X = #{ value = value.ceil }"
  %br
  %br
  На всякий випадок провіримо чи нема дітей в групі
  = value
  за прогнозом.
  %br
  %br
  = "підставимо X = #{ value } в рівняння регресії."
  %br
  = "Y = #{ selection.regression[:a].round(3) } + (#{ selection.regression[:b].round(3) })*#{ value }= #{ (selection.regression[:a].round(3) + selection.regression[:b]*value).round(3) }"
  %br
  Не може бути кількість дітей менше одиниці. Все правильно
  %br
  %br
  %span{ style: 'color: red'}
    Висновок у групі
    = value
    по прогнозу вже нема дітей.
    %br
    = value
    група - це від
    = (value - 1) * selection.cohort_size + 1
    до
    = (value - 1)* selection.cohort_size + selection.cohort_size
    місяців
    %br
    Значить діти старше
    = (value - 1) * selection.cohort_size
    місяців уже практично не страждають розладами ШКТ

app/views/layouts/_selection_by_cohorts.html.haml
%table.au
  %tr
    %td
      Група
    %td
      Вікові категорії
    %td
      Кількість випадків патологій ШКТ
  - selection.group_numbers.each_with_index do |group_number, i|
    %tr
      %td
        = group_number
      %td
        = selection.cohorts[i]
      %td
        = selection.frequencies[i]

app/views/layouts/_xy_total.html.haml
%table.au
  %tr
    %td
      x<sub>i</sub>
    - selection.group_numbers.each do |item|
      %td
        = item
    %td
  %tr
    %td
      y<sub>i</sub>
    - selection.y_data.each do |item|
      %td
        = item
    %td Сума
  %tr
    %td
      x<sub>i</sub>y<sub>i</sub>
    - selection.y_data.each_with_index do |item, index|
      %td
        = item * selection.x_data[index]
    %td
      = selection.xy_sum
%br
= raw "∑x<sub>i</sub>y<sub>i</sub> = #{ selection.xy_sum }"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    = viewport_meta_tag
    %title= content_for?(:title) ? yield(:title) : "Easy KROK"
    = csrf_meta_tags

    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  %body
    %nav.navbar.navbar-default.navbar-fixed-top(role="navigation")
      .container
        .navbar-header
          %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            Correlation and Regression
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li{ class: "#{ 'active' if action_name == 'index'}"}
              = link_to "Осн і Контр", home_path
            %li{ class: "#{ 'active' if action_name == 'group'}"}
              = link_to "50", group_path
            %li{ class: "#{ 'active' if action_name == 'index_fixed'}"}
              = link_to "Осн і Контр(ост дітвак)", home_fixed_path
            %li{ class: "#{ 'active' if action_name == 'group_fixed'}"}
              = link_to "50(ост дітвак)", group_fixed_path
    = yield
    %br
    %br
    %br
    %footer
      %p &copy; 2015